import Head from 'next/head'
import Image from 'next/image'
import Grid from '@mui/material/Grid';
import { Drawer } from '@mui/material';
import { useState } from 'react';
// images
import logo from '../src/images/logo.svg'
import menuIcon from '../src/images/icon-menu.svg'
import closeIcon from '../src/images/icon-menu-close.svg'
// components
import News1 from '@/component/News1';
import News2 from '@/component/News2';
import News3 from '@/component/News3';


export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  const toggleDrawer = () => {
    setIsOpen(!isOpen);
  };
  
  return (
    <>
      <Head>
        <title>Homepage News | Frontend Mentor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <header>
        <div className="header_container">
          <Image src={logo} alt='logo' height={30} width={50} />
          <button className='hamburger-icon' role='open-drawer' onClick={toggleDrawer}>
            <Image src={menuIcon} alt='menu-icon' />
          </button>
          <nav className='desktop_nav'>
            <ul className="desktop_nav_container">
                <li><a href="#">Home</a></li>
                <li><a href="#">New</a></li>
                <li><a href="#">Popular</a></li>
                <li><a href="#">Trending</a></li>
                <li><a href="#">Categories</a></li>
            </ul>
          </nav>
        </div>
      </header>
      <main>
      <Drawer
            anchor={'right'}
            open={isOpen}
            onClose={toggleDrawer}
            
          >
            <div className="drawer-container">
              <button onClick={() => setIsOpen(false)}>
                <Image 
                  src={closeIcon}
                  alt='close-button'
                />
              </button>
              <nav>
                <ul>
                  <li><a href="#">Home</a></li>
                  <li><a href="#">New</a></li>
                  <li><a href="#">Popular</a></li>
                  <li><a href="#">Trending</a></li>
                  <li><a href="#">Categories</a></li>
                </ul>
              </nav>
            </div>
          </Drawer>
        <Grid container spacing={{ xs: 2, md: 4 }}>
          <Grid item xs={12} md={8}>
            <News1 />
          </Grid>
          <Grid item xs={12} md={4}>
            <News2 />
          </Grid>
          <Grid item xs={12} md={12}>
            <News3 />
          </Grid>
        </Grid>
      </main>
    </>
  )
}
